Toggle bike interlay with 'visible' flag instead of filters
tangrams/outdoor-style pull request #154
Opened 2017-03-13 22:29 UTC by matteblair

@nvkelso @sensescape The `visible` layer flag seems to do what you are trying to achieve by querying `global` flags in filter functions. Using `visible` is more efficient for the engine and (in my opinion) reads more naturally. 

I believe this changes preserves the previous behavior, but I haven't been looking at this scene as long as either of you.

2017-03-13 22:34 UTC, nvkelso commented on layers/bike-interlay.yaml
> +# sources:
Good catch!

2017-03-13 22:35 UTC, nvkelso commented
I'll have a look...

2017-03-14 00:47 UTC, nvkelso commented
I think there's a path forward here (to use more `visible` properties rather than always `filter` options), but the current PR ends up showing bike map stuff by default (oops), and removes most minor roads (by default, but restored in bike mode?!). I'll have a closer look tomorrow.

<img width="587" alt="screen shot 2017-03-13 at 17 45 03" src="https://cloud.githubusercontent.com/assets/853051/23881055/f93c3dbe-0814-11e7-864d-4bce142a8787.png">

<img width="653" alt="screen shot 2017-03-13 at 17 44 54" src="https://cloud.githubusercontent.com/assets/853051/23881056/f9533c8a-0814-11e7-95e8-68e82b7f53d9.png">

2017-03-14 00:47 UTC, nvkelso requested changes
I'll noodle around to address comments in https://github.com/tangrams/walkabout-style/pull/154#issuecomment-286288277.

2017-03-14 02:25 UTC, matteblair commented
Whoa, that is not at all what happens in tangram-es. This definitely deserves a closer look!
<img width="1136" alt="screen shot 2017-03-13 at 10 24 11 pm" src="https://cloud.githubusercontent.com/assets/3371850/23883213/ed8fd9ae-083b-11e7-83c9-1dba23c26250.png">

2017-03-15 17:28 UTC, matteblair commented
@bcamper and I were puzzling through this and we discovered that the primary reason this change behaves differently on JS and ES is that the two engines have different interpretations of the layer `visible` flag.

In tangram-es if a layer has `visible: false`, that layer and its sublayers will not be visible, regardless of any `visible` flags in the sublayers.

In tangram-js if a layer has `visible: false`, that layer and its sublayers will not be visible _unless a sublayer has `visible: true`_.

The syntax documentation doesn't specify one way or the other: https://mapzen.com/documentation/tangram/layers/#visible, so before going any further with this PR, we should standardize this behavior.

2017-03-23 23:40 UTC, nvkelso commented
Once Tangram JS v0.12 lands I'll refresh this PR...

2017-04-05 22:39 UTC, nvkelso commented
JS and ES now support `enabled`, I'll have another look at this soon.

2017-05-03 22:11 UTC, nvkelso commented
Fixed in https://github.com/tangrams/walkabout-style/pull/165/commits/82e4c860b0439e1e46d165ae4024134598cae889 via the other PR. Closing this one.

2017-05-03 22:11 UTC, closed without merging